server:
  port: 9090
  devtools:
    restart:
      enabled: true
#  tomcat:
#    accesslog:
#      directory: /Users/hachangjin/IdeaProjects/sample-springboot-webservice/tomcatLogs
#      enabled: true
#      file-date-format: .yyyy-MM-dd
#      max-days: 14
#      pattern: '%h %l %u %t "%r" %s %b %D'
#      prefix: test_access
#      rotate: true
#      suffix: .log
#    basedir: /Users/hachangjin/IdeaProjects/sample-springboot-webservice/tomcatLogs
pagehelper:
  helper-dialect: mysql
  reasonable: true

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul'
    #    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: gkckdwls12
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 10
      minimum-idle: 2
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: false
    default-statement-timeout: 65000
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.sample.board.sprinboot: DEBUG
    jdbc.sqlonly: DEBUG
    org.springframework.web: DEBUG
    com.zaxxer.hikari.HikariDataSource: ERROR
    jdbc.sqltiming: DEBUG
    jdbc.resultsettable: DEBUG
  file:
    path: /logs

#springdoc:
#  version: '@project.version@'
#  api-docs:
#    path: /api-docs
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  swagger-ui:
#    operations-sorter: alpha
#    tags-sorter: alpha
#    path: /swagger-ui.html
#    disable-swagger-default-url: true
#    display-query-params-without-oauth2: true
#  paths-to-match:
#    - /api/v1/**
#    - /test/**